import "./globals.css";
import { Inter } from "next/font/google";
import Sidebar from "@/components/sidebar/sidebar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <script
        src="https://kit.fontawesome.com/d05e64aa0f.js"
        crossorigin="anonymous"
      ></script>
      <body className={inter.className}>
        <div className="dashboard-container">
        <Sidebar />
        {children}
        </div>
      </body>
    </html>
  );
}
